name: Build and Deploy Spring to EC2

on:
  push:
    branches: 
      - deploy-to-ec2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        env:
          DB_USERNAME: moolmin
          DB_PASSWORD: Aaaa123!!
          DB_URL: jdbc:mysql://localhost:3306/community_db
          JWT_KEY: f3c2e1a9d8b7c6e5d4f3g2h1i9j0k1l2m3n4o5p6q7r8s9t0g2h1i9j0k1l2m3n
        run: ./gradlew build test

